/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

//import BLL.MuaBanBLL;
import BLL.SanPhamBLL;
import DTO.SanPhamDTO;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author PC
 */
public class MuaBanGUI extends javax.swing.JFrame {
    SanPhamBLL mbBLL=new SanPhamBLL();
    
    ArrayList<SanPhamDTO> arrSP=new ArrayList<SanPhamDTO>();
        
    DefaultTableModel modelMB = new DefaultTableModel() {
    @Override
    public boolean isCellEditable(int row, int column) {
        return false; // không cho phép chỉnh sửa giá trị các ô trong bảng
    }
    };
    
    DefaultTableModel modelGH = new DefaultTableModel() {
    @Override
    public boolean isCellEditable(int row, int column) {
        return false; // không cho phép chỉnh sửa giá trị các ô trong bảng
    }
    };
    /**
     * Creates new form MuaBan
     */
    public MuaBanGUI() {
        initComponents();
        //Khởi tạo bảng danh sách điện thoại
        jTable_DS.setModel(modelMB);
        modelMB.addColumn("STT");
        modelMB.addColumn("Mã điện thoại");
        modelMB.addColumn("Tên điện thoại");
        modelMB.addColumn("Hãng");
        modelMB.addColumn("Dung lượng");
        modelMB.addColumn("Số lượng");
        modelMB.addColumn("Đơn giá");
        modelMB.addColumn("Hình ảnh");
        modelMB.addColumn("Mức giảm giá");
        modelMB.addColumn("Giá sau giảm");
        //ẩn cột hình ảnh
        TableColumnModel columnModel = jTable_DS.getColumnModel();
        TableColumn column = columnModel.getColumn(7);
        column.setMinWidth(0);
        column.setMaxWidth(0);
        column.setPreferredWidth(0);
        column.setResizable(false);
        loadMBlist();
        
        
        //Khởi tạo bảng danh sách giỏ hàng
        jTable_GH.setModel(modelGH);
        modelGH.addColumn("STT");
        modelGH.addColumn("Tên điện thoại");
        modelGH.addColumn("Hãng");
        modelGH.addColumn("Dung lượng");
        modelGH.addColumn("Số lượng");
        modelGH.addColumn("Mức giảm giá");
        modelGH.addColumn("Giá sau giảm");
        modelGH.addColumn("Thành tiền");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_GH = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_DS = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_MDT = new javax.swing.JTextField();
        jTextField_TDT = new javax.swing.JTextField();
        jTextField_DL = new javax.swing.JTextField();
        jTextField_Gia = new javax.swing.JTextField();
        jComboBox_Hang = new javax.swing.JComboBox<>();
        jSpinner_SL = new javax.swing.JSpinner();
        jButton_TVG = new javax.swing.JButton();
        jLabel_Anh = new javax.swing.JLabel();
        jButton_Xoa = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField_MucGiamGia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("CHI TIẾT SẢN PHẨM");

        jTable_GH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_GH);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("GIỎ HÀNG");

        jTable_DS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_DS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DSMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_DS);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("DANH SÁCH ĐIỆN THOẠI");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Mã điện thoại");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Tên điện thoại");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Hãng");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Dung lượng");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Số lượng");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Giá");

        jTextField_MDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MDTActionPerformed(evt);
            }
        });

        jComboBox_Hang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jButton_TVG.setText("Thêm vào giỏ");
        jButton_TVG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TVGActionPerformed(evt);
            }
        });

        jLabel_Anh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel_Anh.setPreferredSize(new java.awt.Dimension(200, 200));

        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jButton3.setText("Xuất hóa đơn");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Mức giảm giá");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(30, 30, 30)
                                        .addComponent(jTextField_MDT, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel11))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_TDT)
                                            .addComponent(jTextField_DL)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextField_Gia)
                                                    .addComponent(jSpinner_SL)
                                                    .addComponent(jComboBox_Hang, 0, 151, Short.MAX_VALUE)
                                                    .addComponent(jTextField_MucGiamGia))
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jButton_TVG)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 14, Short.MAX_VALUE)
                                .addComponent(jLabel_Anh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_MDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_TDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_DL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jSpinner_SL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_MucGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextField_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jButton_TVG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel_Anh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_MDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MDTActionPerformed

    private void jTable_DSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DSMouseClicked
        int selectedRow = jTable_DS.getSelectedRow();
        if (selectedRow >= 0) {
        // Lấy thông tin của dòng được chọn
        String masp = jTable_DS.getValueAt(selectedRow, 1).toString();
        String tensp = jTable_DS.getValueAt(selectedRow, 2).toString();
        String hang = jTable_DS.getValueAt(selectedRow, 3).toString();
        String dungluong = jTable_DS.getValueAt(selectedRow, 4).toString();
        String gia = jTable_DS.getValueAt(selectedRow, 9).toString();
        String hinhanh = jTable_DS.getValueAt(selectedRow, 7).toString();
        String mucgiamgia=jTable_DS.getValueAt(selectedRow, 8).toString();

        // Cập nhật các trường văn bản và trường khác với thông tin của dòng được chọn
        jTextField_MDT.setText(masp);
        jTextField_TDT.setText(tensp);
        jComboBox_Hang.setSelectedItem(hang);
        jTextField_DL.setText(dungluong);
        jTextField_Gia.setText(gia);
        jTextField_MucGiamGia.setText(mucgiamgia);
        
        // Khóa (disable) các trường văn bản và trường khác
        jTextField_MDT.setEnabled(false);
        jTextField_TDT.setEnabled(false);
        jComboBox_Hang.setEnabled(false);
        jTextField_DL.setEnabled(false);
        jTextField_Gia.setEnabled(false);
        jTextField_MucGiamGia.setEnabled(false);
                
        
        File file = new File(hinhanh);
        ImageIcon imageIcon = new ImageIcon(file.getAbsolutePath());
        Image image = imageIcon.getImage();
        Image scaledImage = image.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
        jLabel_Anh.setIcon(scaledImageIcon);// TODO add your handling code here:
        }
    }//GEN-LAST:event_jTable_DSMouseClicked

    private void jButton_TVGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TVGActionPerformed
                
            // Xử lý sự kiện khi nút "Thêm vào giỏ" được nhấn
        int selectedRow = jTable_DS.getSelectedRow(); // Lấy dòng được chọn từ bảng danh sách điện thoại
        if (selectedRow >= 0) {
            // Lấy thông tin của điện thoại được chọn từ dòng
            String tenDienThoai = jTable_DS.getValueAt(selectedRow, 2).toString();
            String hang = jTable_DS.getValueAt(selectedRow, 3).toString();
            String dungLuong = jTable_DS.getValueAt(selectedRow, 4).toString();
            int soLuong = (int) jSpinner_SL.getValue(); // Lấy giá trị từ JSpinner_SL
            float mucGiamGia = Float.parseFloat(jTable_DS.getValueAt(selectedRow, 8).toString());
            float giaSauGiam = Float.parseFloat(jTable_DS.getValueAt(selectedRow, 9).toString());

            // Thêm thông tin vào bảng giỏ hàng
            int stt = modelGH.getRowCount() + 1;
            Object[] row = {stt, tenDienThoai, hang, dungLuong, soLuong, mucGiamGia, giaSauGiam, soLuong * giaSauGiam};
            modelGH.addRow(row);

            // Gọi phương thức để làm sạch các trường văn bản và combo box của điện thoại được chọn
            clearSelectedPhoneFields();
        }
    }//GEN-LAST:event_jButton_TVGActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        int selectedRow = jTable_GH.getSelectedRow(); // Lấy dòng được chọn từ bảng giỏ hàng
        if (selectedRow >= 0) {
        modelGH.removeRow(selectedRow); // Xóa dòng được chọn từ bảng giỏ hàng
        }
    }//GEN-LAST:event_jButton_XoaActionPerformed
    
    public void loadMBlist(){
        arrSP = mbBLL.getListSanphamWithDiscount();
//        int a = arrSP.size();
//        System.out.print(rootPaneCheckingEnabled);
        for(int i = modelMB.getRowCount()-1;i>=0;i--)
            modelMB.removeRow(i);
        for(int i = 0; i<arrSP.size();i++){
            SanPhamDTO em= arrSP.get(i);
            int stt= i+1;
            String masp= em.getMaSP();
            String tensp = em.getTenSP();
            String hang = em.getHang();
            String dungluong = em.getDungLuong();
            int soluong=em.getSoLuong();
            long dongia=em.getDonGia();
            String hinhanh = em.getHinhAnh();
            long mucgiamgia=(long) em.getMucGiamGia();
            float giasaugiam=em.getGiaSauGiam();
            Object[] row = {stt,masp,tensp,hang,dungluong,soluong,dongia,hinhanh,mucgiamgia,giasaugiam};
            modelMB.addRow(row);
        }
    }
    
    private void clearSelectedPhoneFields() {
        // Các trường văn bản và combo box
        jTextField_MDT.setText("");
        jTextField_TDT.setText("");
        jComboBox_Hang.setSelectedIndex(0);
        jTextField_DL.setText("");
        jTextField_Gia.setText("");
        jTextField_MucGiamGia.setText("");
        jSpinner_SL.setValue(0);

        // Kích hoạt các trường để người dùng có thể chọn điện thoại mới
        jTextField_MDT.setEnabled(true);
        jTextField_TDT.setEnabled(true);
        jComboBox_Hang.setEnabled(true);
        jTextField_DL.setEnabled(true);
        jTextField_Gia.setEnabled(true);
        jTextField_MucGiamGia.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuaBanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuaBanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuaBanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuaBanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuaBanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_TVG;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JComboBox<String> jComboBox_Hang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Anh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_SL;
    private javax.swing.JTable jTable_DS;
    private javax.swing.JTable jTable_GH;
    private javax.swing.JTextField jTextField_DL;
    private javax.swing.JTextField jTextField_Gia;
    private javax.swing.JTextField jTextField_MDT;
    private javax.swing.JTextField jTextField_MucGiamGia;
    private javax.swing.JTextField jTextField_TDT;
    // End of variables declaration//GEN-END:variables
}
