/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.NhaCungCapBLL;
import DAO.NhaCungCapDAO;
import DTO.NhaCungCapDTO;
import DTO.SanPhamNCCDTO;
import DAO.SanPhamNCCDAO;
import BLL.SanPhamNCCBLL;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JDialog;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.JLabel;
/**
 *
 * @author Dao Khanh
 */
public class NhaCungCapGUI extends javax.swing.JPanel {

    NhaCungCapBLL nccBLL=new NhaCungCapBLL();
    
    ArrayList<NhaCungCapDTO> arrNhaCungCap=new ArrayList<NhaCungCapDTO>();
    ArrayList<SanPhamNCCDTO> arrSPNCC=new ArrayList<SanPhamNCCDTO>();
    
    DefaultTableModel modelNCC = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // không cho phép chỉnh sửa giá trị các ô trong bảng
        }
    };
    
    DefaultTableModel modelSPNCC = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // không cho phép chỉnh sửa giá trị các ô trong bảng
        }
    };
    /**
     * Creates new form NhaCungCapGUI
     */
    public NhaCungCapGUI() {
        initComponents();
        
        jTable1.setModel(modelNCC);
        
        
        modelNCC.addColumn("STT");
        modelNCC.addColumn("Mã Nhà Cung Cấp");
        modelNCC.addColumn("Tên Nhà Cung Cấp");
        modelNCC.addColumn("Địa Chỉ");
        modelNCC.addColumn("Số Điện Thoại");
        
        jTable2.setModel(modelSPNCC);
        
        modelSPNCC.addColumn("STT");
        modelSPNCC.addColumn("Mã Nhà Cung Cấp");
        modelSPNCC.addColumn("Mã Sản Phẩm");
        modelSPNCC.addColumn("Số Lượng");
        modelSPNCC.addColumn("Đơn Giá");
        
        loadNCClist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SanPhamNCC_Dialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        Them_SPNCC = new javax.swing.JButton();
        Dong_SPNCC = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jButton_Huy = new javax.swing.JButton();
        jButton_Them = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField_DiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_SDT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Ten = new javax.swing.JTextField();
        jButton_SanPhamNCC = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jComboBox_SearchType1 = new javax.swing.JComboBox<>();
        jTextField_Search = new javax.swing.JTextField();
        jButton_Search = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        SanPhamNCC_Dialog.setModal(true);
        SanPhamNCC_Dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                SanPhamNCC_DialogWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Them San Pham Cho Nha Cung Cap");

        jLabel2.setText("Ma Nha Cung Cap");

        jLabel3.setText("Ma San Pham");

        jLabel4.setText("So Luong");

        jLabel5.setText("Don Gia");

        jScrollPane2.setViewportView(jTextPane1);

        jScrollPane3.setViewportView(jTextPane2);

        jScrollPane4.setViewportView(jTextPane3);

        jScrollPane6.setViewportView(jTextPane5);

        Them_SPNCC.setBackground(new java.awt.Color(0, 51, 255));
        Them_SPNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Them_SPNCC.setText("Them");
        Them_SPNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Them_SPNCCActionPerformed(evt);
            }
        });

        Dong_SPNCC.setBackground(new java.awt.Color(51, 51, 255));
        Dong_SPNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dong_SPNCC.setText("Dong");
        Dong_SPNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dong_SPNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(Them_SPNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(Dong_SPNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Them_SPNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dong_SPNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SanPhamNCC_DialogLayout = new javax.swing.GroupLayout(SanPhamNCC_Dialog.getContentPane());
        SanPhamNCC_Dialog.getContentPane().setLayout(SanPhamNCC_DialogLayout);
        SanPhamNCC_DialogLayout.setHorizontalGroup(
            SanPhamNCC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SanPhamNCC_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SanPhamNCC_DialogLayout.setVerticalGroup(
            SanPhamNCC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SanPhamNCC_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jTextPane4);

        setLayout(null);

        jButton_Huy.setText("Hủy");
        jButton_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HuyActionPerformed(evt);
            }
        });
        add(jButton_Huy);
        jButton_Huy.setBounds(802, 199, 100, 23);

        jButton_Them.setText("Thêm");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });
        add(jButton_Them);
        jButton_Them.setBounds(101, 199, 100, 23);

        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });
        add(jButton_Sua);
        jButton_Sua.setBounds(334, 199, 100, 23);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Địa Chỉ");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Số Điện Thoại");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tên Nhà Cung Cấp");

        jButton_SanPhamNCC.setText("Thêm Sản Phẩm Nhà Cung Cấp");
        jButton_SanPhamNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SanPhamNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField_Ten)
                    .addComponent(jTextField_SDT, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addGap(146, 146, 146)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_SanPhamNCC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_Ten))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_SanPhamNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );

        add(jPanel1);
        jPanel1.setBounds(6, 6, 960, 187);

        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });
        add(jButton_Xoa);
        jButton_Xoa.setBounds(579, 199, 100, 23);

        jComboBox_SearchType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Nhà Cung Cấp","Tên Nhà Cung Cấp" }));
        jComboBox_SearchType1.setPreferredSize(new java.awt.Dimension(100, 30));
        jComboBox_SearchType1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_SearchType1ItemStateChanged(evt);
            }
        });
        jComboBox_SearchType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_SearchType1ActionPerformed(evt);
            }
        });
        add(jComboBox_SearchType1);
        jComboBox_SearchType1.setBounds(237, 228, 121, 44);

        jTextField_Search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_SearchFocusGained(evt);
            }
        });
        add(jTextField_Search);
        jTextField_Search.setBounds(364, 228, 261, 44);

        jButton_Search.setText("Tìm Kiếm");
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });
        add(jButton_Search);
        jButton_Search.setBounds(631, 228, 108, 44);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        add(jPanel2);
        jPanel2.setBounds(6, 278, 454, 100);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(jPanel4);
        jPanel4.setBounds(972, 278, 100, 100);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        add(jPanel5);
        jPanel5.setBounds(487, 278, 479, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HuyActionPerformed
        // TODO add your handling code here:
        jTextField_Ten.setText("");
        jTextField_DiaChi.setText("");
        jTextField_SDT.setText("");

    }//GEN-LAST:event_jButton_HuyActionPerformed

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        // TODO add your handling code here:
        // Lấy dữ liệu từ jTextField
        String ten = jTextField_Ten.getText();
        String sdt = jTextField_SDT.getText();
        String diachi = jTextField_DiaChi.getText();
        
        
        try{
            // Kiểm tra nếu cả hai trường không rỗng
            if (!ten.isEmpty() &&  !sdt.isEmpty() && !diachi.isEmpty())
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
            else{
                NhaCungCapDTO ncc=new NhaCungCapDTO();
                if(arrNhaCungCap.size()==0){
                    ncc.setMaNCC("NCC001");
                }
                else {
                    NhaCungCapDTO NV = arrNhaCungCap.get(arrNhaCungCap.size()-1);
                    int id = Integer.parseInt(NV.getMaNCC().substring(3));

                    if(id<=9)
                    ncc.setMaNCC("NCC00"+(id+1));
                    else if(id>=10 && id<=99)
                    ncc.setMaNCC("NCC0"+(id+1));
                    else
                    ncc.setMaNCC("NCC"+(id+1));
                }
                ncc.setTenNCC(jTextField_Ten.getText());
                ncc.setDiaChiNCC(jTextField_DiaChi.getText());
                ncc.setSDTNCC(jTextField_SDT.getText());

                nccBLL.addNCC(ncc);
                loadNCClist();
            }

        }
        catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        }
        // Thêm dữ liệu mới vào mô hình

    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        String id = modelNCC.getValueAt(i, 1).toString();
        String name = jTextField_Ten.getText();
        String diachi = jTextField_DiaChi.getText();
        String sdt = jTextField_SDT.getText();

        nccBLL.UpNCC(id,name,diachi,sdt);

        loadNCClist();

    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        // TODO add your handling code here:
        int i= jTable1.getSelectedRow();
        if(i>=0){
            nccBLL.delNCC(modelNCC.getValueAt(i,1).toString());
            loadNCClist();
        }

    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jTextField_SearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SearchFocusGained
        // TODO add your handling code here:
        if(jTextField_Search!=null){
            jTextField_Search.setText("");
            jTextField_Search.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jTextField_SearchFocusGained

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        // TODO add your handling code here:
        String selectedValue = jComboBox_SearchType1.getSelectedItem().toString();

        // Lấy giá trị từ jTextField
        String searchText = jTextField_Search.getText().trim();

        if ("Mã Nhà Cung Cấp".equals(selectedValue)) {
            // Tìm kiếm theo ID trong jTable
            searchByID(searchText);
        } else if ("Tên Nhà Cung Cấp".equals(selectedValue)) {
            // Tìm kiếm theo Name trong jTable
            searchByName(searchText);
        } else {
            // Hiển thị thông báo hoặc xử lý lỗi nếu giá trị không hợp lệ
            JOptionPane.showMessageDialog(this, "Giá trị không hợp lệ.");
        }
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jButton_SanPhamNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SanPhamNCCActionPerformed
        // TODO add your handling code here:
        SanPhamNCC_Dialog.setSize(500, 600);
       SanPhamNCC_Dialog.setVisible(true);
        
        
    }//GEN-LAST:event_jButton_SanPhamNCCActionPerformed

    private void jComboBox_SearchType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_SearchType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_SearchType1ActionPerformed

    private void jComboBox_SearchType1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_SearchType1ItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String selectedValue = jComboBox_SearchType1.getSelectedItem().toString();

            // Thiết lập giá trị mẫu cho jTextField dựa trên mục đã chọn
            setTextFieldPlaceholderNCC(selectedValue);
        }
    }//GEN-LAST:event_jComboBox_SearchType1ItemStateChanged
//Thêm sản phẩm ncc-----------------------------------------------------------------------------------
    private void Them_SPNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Them_SPNCCActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Them_SPNCCActionPerformed

    private void SanPhamNCC_DialogWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_SanPhamNCC_DialogWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SanPhamNCC_DialogWindowActivated

    private void Dong_SPNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dong_SPNCCActionPerformed
        // TODO add your handling code here:
        SanPhamNCC_Dialog.setVisible(false);
    }//GEN-LAST:event_Dong_SPNCCActionPerformed
                                                                                               

    private void searchByID(String id) {
    // Thực hiện tìm kiếm theo ID trong jTable và cập nhật kết quả lên jTable
        
        modelNCC.setRowCount(0); // Xóa tất cả dữ liệu hiện có trong jTable
        int stt=1;
        for (int i = 0; i < modelNCC.getRowCount(); i++) {
            String rowData = modelNCC.getValueAt(i, 1).toString(); // Cột ID là cột 0
            if (rowData.equals(id)) {
                // Nếu tìm thấy ID, thêm hàng tương ứng vào jTable
                
                Object[] row = new Object[]{stt,modelNCC.getValueAt(i, 1), modelNCC.getValueAt(i, 2),modelNCC.getValueAt(i, 3),modelNCC.getValueAt(i, 4),modelNCC.getValueAt(i, 5)};
                modelNCC.addRow(row);
                stt++;
                
            }
        }
    }

    private void searchByName(String name) {
        // Thực hiện tìm kiếm theo Name trong jTable và cập nhật kết quả lên jTable
        
        modelNCC.setRowCount(0); // Xóa tất cả dữ liệu hiện có trong jTable
        int stt=1;
        for (int i = 0; i < modelNCC.getRowCount(); i++) {
            String rowData = modelNCC.getValueAt(i, 2).toString(); // Cột Name là cột 1
            if (rowData.equalsIgnoreCase(name)) {
                // Nếu tìm thấy Name, thêm hàng tương ứng vào jTable
                Object[] row = new Object[]{modelNCC.getValueAt(i, 1), modelNCC.getValueAt(i, 2),modelNCC.getValueAt(i, 3),modelNCC.getValueAt(i, 4),modelNCC.getValueAt(i, 5)};
                modelNCC.addRow(row);
                stt++;
            }
        }
    }
    private void setTextFieldPlaceholderNCC(String selectedValue) {
        String placeholderText = ""; // Chuỗi mẫu sẽ được hiển thị trong jTextField

        // Xác định chuỗi mẫu dựa trên mục đã chọn
        if ("Mã Nhà Cung Cấp".equals(selectedValue)) {
            placeholderText = "Ví dụ: NCC001";
        }else if ("Tên Nhà Cung Cấp".equals(selectedValue)) {
            placeholderText = "Ví dụ: CTY Cổ Phần ODS";
        }
        

        // Thiết lập giá trị mẫu cho jTextField
        jTextField_Search.setText(placeholderText);
    }
    public void loadNCClist(){
        arrNhaCungCap = nccBLL.getListNhaCungCap();
//        int a = arrNCC.size();
//        System.out.print(rootPaneCheckingEnabled);
        for(int i = modelNCC.getRowCount()-1;i>=0;i--)
            modelNCC.removeRow(i);
        for(int i = 0; i<arrNhaCungCap.size();i++){
            NhaCungCapDTO em= arrNhaCungCap.get(i);
            int stt= i+1;
            String id= em.getMaNCC();
            String name = em.getTenNCC();
            String address = em.getDiaChiNCC();
            String sdt = em.getSDTNCC();
            
            Object[] row = {stt,id,name,address,sdt};
            modelNCC.addRow(row);
        }
    }
    
    public void SanPhamNCC()
    {
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dong_SPNCC;
    private javax.swing.JDialog SanPhamNCC_Dialog;
    private javax.swing.JButton Them_SPNCC;
    private javax.swing.JButton jButton_Huy;
    private javax.swing.JButton jButton_SanPhamNCC;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JComboBox<String> jComboBox_SearchType1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField_DiaChi;
    private javax.swing.JTextField jTextField_SDT;
    private javax.swing.JTextField jTextField_Search;
    private javax.swing.JTextField jTextField_Ten;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    // End of variables declaration//GEN-END:variables


}
