/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.NhaCungCapBLL;
import DAO.NhaCungCapDAO;
import DTO.NhaCungCapDTO;
import DTO.SanPhamNCCDTO;
import DAO.SanPhamNCCDAO;
import BLL.SanPhamNCCBLL;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author Dao Khanh
 */
public class NhaCungCapGUI extends javax.swing.JPanel {

    NhaCungCapBLL nccBLL=new NhaCungCapBLL();
    SanPhamNCCBLL spnccBLL = new SanPhamNCCBLL();
    
    ArrayList<NhaCungCapDTO> arrNhaCungCap=new ArrayList<NhaCungCapDTO>();
    ArrayList<SanPhamNCCDTO> arrSPNCC=new ArrayList<SanPhamNCCDTO>();
    Connection conn;
    private JComboBox<String> comboBox;
    DefaultTableModel modelNCC = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // không cho phép chỉnh sửa giá trị các ô trong bảng
        }
    };
    
    DefaultTableModel modelSPNCC = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // không cho phép chỉnh sửa giá trị các ô trong bảng
        }
    };
    /**
     * Creates new form NhaCungCapGUI
     */
    public NhaCungCapGUI() {
        initComponents();
        
        jTable1.setModel(modelNCC);
        
        
        modelNCC.addColumn("STT");
        modelNCC.addColumn("Mã Nhà Cung Cấp");
        modelNCC.addColumn("Tên Nhà Cung Cấp");
        modelNCC.addColumn("Địa Chỉ");
        modelNCC.addColumn("Số Điện Thoại");
        
        jTable2.setModel(modelSPNCC);
        
        modelSPNCC.addColumn("STT");
        modelSPNCC.addColumn("Mã Nhà Cung Cấp");
        modelSPNCC.addColumn("Mã Sản Phẩm");
        
        loadNCClist();
        loadSPNCCList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SanPhamNCC_Dialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Them_SPNCC = new javax.swing.JButton();
        Dong_SPNCC = new javax.swing.JButton();
        jComboBox_IDSP = new javax.swing.JComboBox<>();
        jComboBox_IDNCC = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jButton_Huy = new javax.swing.JButton();
        jButton_Them = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField_SDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_DiaChi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Ten = new javax.swing.JTextField();
        jButton_SanPhamNCC = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Ma = new javax.swing.JTextField();
        jButton_Xoa = new javax.swing.JButton();
        jComboBox_SearchType1 = new javax.swing.JComboBox<>();
        jTextField_Search = new javax.swing.JTextField();
        jButton_Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        SanPhamNCC_Dialog.setModal(true);
        SanPhamNCC_Dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                SanPhamNCC_DialogWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thêm Sản Phẩm Cho Nhà Cung Cấp");

        jLabel2.setText("Mã Nhà Cung Cấp");

        jLabel3.setText("Mã Sản Phẩm");

        Them_SPNCC.setBackground(new java.awt.Color(204, 255, 255));
        Them_SPNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Them_SPNCC.setText("Thêm");
        Them_SPNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Them_SPNCCActionPerformed(evt);
            }
        });

        Dong_SPNCC.setBackground(new java.awt.Color(204, 255, 255));
        Dong_SPNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dong_SPNCC.setText("Đóng");
        Dong_SPNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dong_SPNCCActionPerformed(evt);
            }
        });

        jComboBox_IDSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox_IDNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_IDNCC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_IDNCCItemStateChanged(evt);
            }
        });
        jComboBox_IDNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_IDNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(42, 302, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox_IDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(Them_SPNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(Dong_SPNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(205, Short.MAX_VALUE)
                    .addComponent(jComboBox_IDNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(32, 32, 32)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_IDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Them_SPNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dong_SPNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(jComboBox_IDNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(358, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout SanPhamNCC_DialogLayout = new javax.swing.GroupLayout(SanPhamNCC_Dialog.getContentPane());
        SanPhamNCC_Dialog.getContentPane().setLayout(SanPhamNCC_DialogLayout);
        SanPhamNCC_DialogLayout.setHorizontalGroup(
            SanPhamNCC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SanPhamNCC_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SanPhamNCC_DialogLayout.setVerticalGroup(
            SanPhamNCC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SanPhamNCC_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jTextPane4);

        setLayout(null);

        jButton_Huy.setText("Hủy");
        jButton_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HuyActionPerformed(evt);
            }
        });
        add(jButton_Huy);
        jButton_Huy.setBounds(802, 199, 100, 23);

        jButton_Them.setText("Thêm");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });
        add(jButton_Them);
        jButton_Them.setBounds(101, 199, 100, 23);

        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });
        add(jButton_Sua);
        jButton_Sua.setBounds(334, 199, 100, 23);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));
        jPanel1.setEnabled(false);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Số Điện Thoại");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Địa Chỉ");

        jTextField_Ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TenActionPerformed(evt);
            }
        });

        jButton_SanPhamNCC.setText("Thêm Sản Phẩm Nhà Cung Cấp");
        jButton_SanPhamNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SanPhamNCCActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tên Nhà Cung Cấp");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Mã Nhà Cung Cấp");

        jTextField_Ma.setEditable(false);
        jTextField_Ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTextField_Ma, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_SanPhamNCC))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_SanPhamNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_Ma, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        add(jPanel1);
        jPanel1.setBounds(6, 6, 960, 196);

        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });
        add(jButton_Xoa);
        jButton_Xoa.setBounds(579, 199, 100, 23);

        jComboBox_SearchType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Nhà Cung Cấp","Tên Nhà Cung Cấp" }));
        jComboBox_SearchType1.setPreferredSize(new java.awt.Dimension(100, 30));
        jComboBox_SearchType1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_SearchType1ItemStateChanged(evt);
            }
        });
        jComboBox_SearchType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_SearchType1ActionPerformed(evt);
            }
        });
        add(jComboBox_SearchType1);
        jComboBox_SearchType1.setBounds(237, 228, 121, 44);

        jTextField_Search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_SearchFocusGained(evt);
            }
        });
        jTextField_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearchActionPerformed(evt);
            }
        });
        add(jTextField_Search);
        jTextField_Search.setBounds(364, 228, 261, 44);

        jButton_Search.setText("Tìm Kiếm");
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });
        add(jButton_Search);
        jButton_Search.setBounds(631, 228, 108, 44);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 300, 540, 238);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable2);

        add(jScrollPane7);
        jScrollPane7.setBounds(560, 300, 390, 240);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HuyActionPerformed
        // TODO add your handling code here:
        jTextField_Ma.setText("");
        jTextField_Ten.setText("");
        jTextField_DiaChi.setText("");
        jTextField_SDT.setText("");

    }//GEN-LAST:event_jButton_HuyActionPerformed

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        // TODO add your handling code here:
        // Lấy dữ liệu từ jTextField
        String ten = jTextField_Ten.getText();
        String diachi = jTextField_DiaChi.getText();
        String sdt = jTextField_SDT.getText();
        
        
        
        try{
            // Kiểm tra nếu cả hai trường không rỗng
            if (ten.isEmpty() &&  sdt.isEmpty() && diachi.isEmpty())
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
            else{
                if (isValidPhoneNumber(sdt)) {
                    NhaCungCapDTO ncc=new NhaCungCapDTO();

                    String newMaNCC = generateMaNCC();
                    ncc.setMaNCC(newMaNCC);
                    
                    ncc.setTenNCC(jTextField_Ten.getText());
                    ncc.setDiaChiNCC(jTextField_DiaChi.getText());
                    ncc.setSDTNCC(jTextField_SDT.getText());

                    nccBLL.addNCC(ncc);
                    loadNCClist();

                    jTextField_Ten.setText("");
                    jTextField_DiaChi.setText("");
                    jTextField_SDT.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ. Vui lòng kiểm tra lại.");
                }
            }
        }
        catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_jButton_ThemActionPerformed

    public String generateMaNCC()
    {
       String newMaNCC="";
       if (arrNhaCungCap.isEmpty()) {
            newMaNCC = "NCC01";
        } else {
           int newId = 1;
           boolean isUnique = false;
           
           while (!isUnique) {
               newMaNCC = "NCC" + String.format("%02d", newId);
               isUnique = isMaNCCUnique(newMaNCC);
               
               if (!isUnique) {
                   newId++;
               }
           }
        }
       return newMaNCC;
    }
    
    private boolean isMaNCCUnique(String maNCC) {
        for (NhaCungCapDTO ncc : arrNhaCungCap) {
            if (ncc.getMaNCC().equals(maNCC)) {
                return false;
            }
        }
        return true;
    }
    
    private boolean isValidPhoneNumber(String phoneNumber) {
        String regex = "(84|0)(2[0-9]|3[2-9]|4[0-9]|5[6-9]|6[2-9]|7[0-9]|8[1-9]|9[0-9])[0-9]{7,8}";
        return phoneNumber.matches(regex);
    }
    
    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        // TODO add your handling code here:
        //String maNCC = generateMaNCC();
        String maNCC = jTextField_Ma.getText();
        String tenNCC = jTextField_Ten.getText();
        String sdtNCC = jTextField_SDT.getText();
        String dcNCC = jTextField_DiaChi.getText();
        NhaCungCapDTO ncc = new NhaCungCapDTO();
        try {
            if(tenNCC.isEmpty() || sdtNCC.isEmpty() || dcNCC.isEmpty() ){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
            }
            else {
                ncc.setMaNCC(maNCC);
                ncc.setTenNCC(tenNCC);
                ncc.setSDTNCC(sdtNCC);
                ncc.setDiaChiNCC(dcNCC);
                
                nccBLL.UpNCC(ncc);
                 loadNCClist();
                JOptionPane.showMessageDialog(this, "Sửa thông tin Nhà Cung Cấp thành công");
                
            }
        }catch(Exception ex){
             ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thong tin khong hop le");
        }
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        // TODO add your handling code here:
        int i= jTable1.getSelectedRow();
        
        if(i>=0){
            nccBLL.delNCC(modelNCC.getValueAt(i,1).toString());
            loadNCClist();
        }
        
        
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jTextField_SearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SearchFocusGained
        // TODO add your handling code here:
        if(jTextField_Search!=null){
            jTextField_Search.setText("");
            jTextField_Search.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jTextField_SearchFocusGained

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        String selectedValue = jComboBox_SearchType1.getSelectedItem().toString();
        String search = jTextField_Search.getText().trim();
        
        if("Mã Nhà Cung Cấp".equals(selectedValue)){
            searchByID(search);
        }else if("Tên Nhà Cung Cấp".equals(selectedValue)){
            searchByName(search);
        }else {
            JOptionPane.showMessageDialog(this, "Giá trị không hợp lệ.");
        }
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jButton_SanPhamNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SanPhamNCCActionPerformed
        // TODO add your handling code here:
       SanPhamNCC_Dialog.setSize(450, 450);
       
       DoMaVaoComBoBox(jComboBox_IDNCC, "NhaCungCap", "MaNCC");
       DoMaVaoComBoBox(jComboBox_IDSP, "SanPham", "MaSP");
       SanPhamNCC_Dialog.setVisible(true);
    }//GEN-LAST:event_jButton_SanPhamNCCActionPerformed

    private void jComboBox_SearchType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_SearchType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_SearchType1ActionPerformed

    private void jComboBox_SearchType1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_SearchType1ItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String selectedValue = jComboBox_SearchType1.getSelectedItem().toString();

            // Thiết lập giá trị mẫu cho jTextField dựa trên mục đã chọn
            setTextFieldPlaceholderNCC(selectedValue);
        }
    }//GEN-LAST:event_jComboBox_SearchType1ItemStateChanged
//------------------------------Thêm sản phẩm ncc-----------------------------------------------------------------------------------
    private void Them_SPNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Them_SPNCCActionPerformed
        // TODO add your handling code here:
        String maNCC = jComboBox_IDNCC.getSelectedItem().toString();
        String maSPNCC = jComboBox_IDSP.getSelectedItem().toString();
        
        try {
            // Kiểm tra nếu cả hai trường không rỗng
            SanPhamNCCDTO spncc=new SanPhamNCCDTO();

            spncc.setMaNCC((String) jComboBox_IDNCC.getSelectedItem());
            spncc.setMaSP((String) jComboBox_IDSP.getSelectedItem());

            spnccBLL.addSPNCC(spncc);
            loadSPNCCList();
 
            }
        catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_Them_SPNCCActionPerformed

    private void SanPhamNCC_DialogWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_SanPhamNCC_DialogWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SanPhamNCC_DialogWindowActivated

    private void Dong_SPNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dong_SPNCCActionPerformed
        // TODO add your handling code here:
        SanPhamNCC_Dialog.setVisible(false);
    }//GEN-LAST:event_Dong_SPNCCActionPerformed

    private void jTextField_TenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TenActionPerformed

    private void jTextField_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SearchActionPerformed

    private void jTextField_MaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_MaActionPerformed
    public void DoMaVaoComBoBox(JComboBox<String> comboBox, String tableName, String columnName) {
        connecttoDatabase();
        
        ArrayList<String> maNCCList = new ArrayList<>();
        try {
            Statement pstmt = conn.createStatement();
            String query = "SELECT " + columnName + " FROM " + tableName;
            ResultSet rs = pstmt.executeQuery(query);
            

            while(rs.next()){
                maNCCList.add(rs.getString(columnName));
            }
            DefaultComboBoxModel cbbID = new DefaultComboBoxModel<>(maNCCList.toArray(new String[0]));
            comboBox.setModel(cbbID);
            rs.close();
            pstmt.close();
//            SanPhamNCC_Dialog.setVisible(true);
        }catch (SQLException e){
            e.printStackTrace();
        }
    }
    
    
    private void jComboBox_IDNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_IDNCCActionPerformed
        // TODO add your handling code here:
//       
    }//GEN-LAST:event_jComboBox_IDNCCActionPerformed

    private void jComboBox_IDNCCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_IDNCCItemStateChanged
        // TODO add your handling code here:
//       
    }//GEN-LAST:event_jComboBox_IDNCCItemStateChanged

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int x = jTable1.getSelectedRow();
        if(x>0){
            jTextField_Ma.setText(jTable1.getValueAt(x, 1) + "");
            jTextField_Ten.setText(jTable1.getValueAt(x, 2) + "");
            jTextField_DiaChi.setText(jTable1.getValueAt(x, 3) + "");
            jTextField_SDT.setText(jTable1.getValueAt(x, 4) + "");
            jTextField_Ma.setEnabled(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked
                                                                                               
    public void connecttoDatabase ()
    {
        try{
            String connectionUrl = "jdbc:sqlserver://localhost:1433;DatabaseName=QLCH3;"
            + "user=sa;password=123456;encrypt=true;trustServerCertificate=true";
            conn = DriverManager.getConnection(connectionUrl);
        }catch(Exception e){
            e.printStackTrace();
        }
    }    
    private void searchByID(String id) {
    // Thực hiện tìm kiếm theo ID trong jTable và cập nhật kết quả lên jTable
        DefaultTableModel md = (DefaultTableModel) jTable1.getModel();
        md.setRowCount(0);
        
        connecttoDatabase();
        try {
            if(conn != null){
                String query = "SELECT * FROM NhaCungCap WHERE MaNCC LIKE ?";
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setString(1, "%" + id + "%");
                ResultSet rs = pstmt.executeQuery();
                int stt = 1;
                
                while(rs.next()){
                    String MaNCC = rs.getString("MaNCC");
                    String TenNCC = rs.getString("TenNCC");
                    String DiaChiNCC = rs.getString("DiaChiNCC");
                    String SDTNCC = rs.getString("SDTNCC");
                    
                    md.addRow(new Object[]{stt++, MaNCC, TenNCC, DiaChiNCC, SDTNCC});
                }
                
                rs.close();
                pstmt.close();
                conn.close();
            }else {
                JOptionPane.showMessageDialog(this, "Lỗi kết nối.");
            }
            
        }catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn.");
        }
    }

    private void searchByName(String name) {
        // Thực hiện tìm kiếm theo Name trong jTable và cập nhật kết quả lên jTable
        DefaultTableModel md = (DefaultTableModel) jTable1.getModel();
        md.setRowCount(0);
        
        connecttoDatabase();
        try {
            if(conn != null){
                String query = "SELECT * FROM NhaCungCap WHERE TenNCC LIKE ?";
                PreparedStatement pstmt = conn.prepareStatement(query);
                pstmt.setString(1, "%" + name + "%");
                ResultSet rs = pstmt.executeQuery();
                int stt = 1;
                while(rs.next()){
                    String MaNCC = rs.getString("MaNCC");
                    String TenNCC = rs.getString("TenNCC");
                    String DiaChiNCC = rs.getString("DiaChiNCC");
                    String SDTNCC = rs.getString("SDTNCC");
                    
                    md.addRow(new Object[]{stt++, MaNCC, TenNCC, DiaChiNCC, SDTNCC});
                }
                
                rs.close();
                pstmt.close();
                conn.close();
            }else {
                JOptionPane.showMessageDialog(this, "Lỗi kết nối.");
            }
            
        }catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn.");
        }
       
    }
    private void setTextFieldPlaceholderNCC(String selectedValue) {
        String placeholderText = ""; // Chuỗi mẫu sẽ được hiển thị trong jTextField

        // Xác định chuỗi mẫu dựa trên mục đã chọn
        if ("Mã Nhà Cung Cấp".equals(selectedValue)) {
            placeholderText = "Ví dụ: NCC001";
        }else if ("Tên Nhà Cung Cấp".equals(selectedValue)) {
            placeholderText = "Ví dụ: CTY Cổ Phần ODS";
        }
        

        // Thiết lập giá trị mẫu cho jTextField
        jTextField_Search.setText(placeholderText);
    }
    public void loadNCClist(){
        int n = 0;
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        model.setRowCount(0);
        arrNhaCungCap = nccBLL.getListNhaCungCap();
//        int a = arrNCC.size();
//        System.out.print(rootPaneCheckingEnabled);
        for(int i = modelNCC.getRowCount()-1;i>=0;i--)
            modelNCC.removeRow(i);
        for(int i = 0; i<arrNhaCungCap.size();i++){
            NhaCungCapDTO em= arrNhaCungCap.get(i);
            int stt= i+1;
            String id= em.getMaNCC();
            String name = em.getTenNCC();
            String address = em.getDiaChiNCC();
            String sdt = em.getSDTNCC();
            
            Object[] row = {stt,id,name,address,sdt};
            modelNCC.addRow(row);
        }
    }
    
    public void loadSPNCCList() {
        DefaultTableModel model = (DefaultTableModel) this.jTable2.getModel();
        model.setRowCount(0);
        arrSPNCC = spnccBLL.getListSanPhamNCC();
        for(int i = modelSPNCC.getRowCount()-1;i>=0;i--)
            modelSPNCC.removeRow(i);
        for(int i = 0; i<arrSPNCC.size();i++){
            SanPhamNCCDTO em = arrSPNCC.get(i);
            int stt = i+1;
            String idncc = em.getMaNCC();
            String idsp = em.getMaSP();
            
            Object[] row = {stt,idncc,idsp};
            modelSPNCC.addRow(row);
            
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dong_SPNCC;
    private javax.swing.JDialog SanPhamNCC_Dialog;
    private javax.swing.JButton Them_SPNCC;
    private javax.swing.JButton jButton_Huy;
    private javax.swing.JButton jButton_SanPhamNCC;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JComboBox<String> jComboBox_IDNCC;
    private javax.swing.JComboBox<String> jComboBox_IDSP;
    private javax.swing.JComboBox<String> jComboBox_SearchType1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField_DiaChi;
    private javax.swing.JTextField jTextField_Ma;
    private javax.swing.JTextField jTextField_SDT;
    private javax.swing.JTextField jTextField_Search;
    private javax.swing.JTextField jTextField_Ten;
    private javax.swing.JTextPane jTextPane4;
    // End of variables declaration//GEN-END:variables


}
