/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.NhaCungCapBLL;
import DAO.NhaCungCapDAO;
import DTO.NhaCungCapDTO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.JLabel;
/**
 *
 * @author Dao Khanh
 */
public class NhaCungCapGUI extends javax.swing.JPanel {

    NhaCungCapBLL nccBLL=new NhaCungCapBLL();
    
    ArrayList<NhaCungCapDTO> arrNhaCungCap=new ArrayList<NhaCungCapDTO>();
    
    DefaultTableModel modelNCC = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // không cho phép chỉnh sửa giá trị các ô trong bảng
        }
    };
    /**
     * Creates new form NhaCungCapGUI
     */
    public NhaCungCapGUI() {
        initComponents();
        
        jTable1.setModel(modelNCC);
        
        
        modelNCC.addColumn("STT");
        modelNCC.addColumn("Mã Nhà Cung Cấp");
        modelNCC.addColumn("Tên Nhà Cung Cấp");
        modelNCC.addColumn("Địa Chỉ");
        modelNCC.addColumn("Số Điện Thoại");
        
        loadNCClist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Huy = new javax.swing.JButton();
        jButton_Them = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_DiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_SDT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Ten = new javax.swing.JTextField();
        jCheckBox_OPPO = new javax.swing.JCheckBox();
        jCheckBox_SAMSUNG = new javax.swing.JCheckBox();
        jCheckBox_APPLE = new javax.swing.JCheckBox();
        jCheckBox_VIVO = new javax.swing.JCheckBox();
        jCheckBox_REALME = new javax.swing.JCheckBox();
        jButton_Xoa = new javax.swing.JButton();
        jComboBox_SearchType = new javax.swing.JComboBox<>();
        jTextField_Search = new javax.swing.JTextField();
        jButton_Search = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jButton_Huy.setText("Hủy");
        jButton_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HuyActionPerformed(evt);
            }
        });

        jButton_Them.setText("Thêm");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });

        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Loại Sản Phẩm");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Địa Chỉ");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Số Điện Thoại");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tên Nhà Cung Cấp");

        jCheckBox_OPPO.setText("OPPO");
        jCheckBox_OPPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_OPPOActionPerformed(evt);
            }
        });

        jCheckBox_SAMSUNG.setText("SAMSUNG");
        jCheckBox_SAMSUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_SAMSUNGActionPerformed(evt);
            }
        });

        jCheckBox_APPLE.setText("APPLE");
        jCheckBox_APPLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_APPLEActionPerformed(evt);
            }
        });

        jCheckBox_VIVO.setText("VIVO");
        jCheckBox_VIVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_VIVOActionPerformed(evt);
            }
        });

        jCheckBox_REALME.setText("REALME");
        jCheckBox_REALME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_REALMEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField_Ten)
                    .addComponent(jTextField_SDT, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addGap(146, 146, 146)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox_APPLE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox_VIVO))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox_OPPO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox_SAMSUNG))
                            .addComponent(jCheckBox_REALME))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_Ten))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_SDT, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jCheckBox_OPPO, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_SAMSUNG, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_APPLE, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_VIVO, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox_REALME, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );

        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jComboBox_SearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Nhân Viên","Tên Nhân Viên" }));
        jComboBox_SearchType.setPreferredSize(new java.awt.Dimension(100, 30));
        jComboBox_SearchType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_SearchTypeItemStateChanged(evt);
            }
        });
        jComboBox_SearchType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_SearchTypeActionPerformed(evt);
            }
        });

        jTextField_Search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_SearchFocusGained(evt);
            }
        });

        jButton_Search.setText("Tìm Kiếm");
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(jComboBox_SearchType, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jButton_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)
                                .addComponent(jButton_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145)
                                .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123)
                                .addComponent(jButton_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Them)
                    .addComponent(jButton_Sua)
                    .addComponent(jButton_Xoa)
                    .addComponent(jButton_Huy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_SearchType, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jTextField_Search))
                .addGap(8, 8, 8)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HuyActionPerformed
        // TODO add your handling code here:
        jTextField_Ten.setText("");
        jTextField_DiaChi.setText("");
        jTextField_SDT.setText("");

    }//GEN-LAST:event_jButton_HuyActionPerformed

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        // TODO add your handling code here:
        // Lấy dữ liệu từ jTextField
        String ten = jTextField_Ten.getText();
        String sdt = jTextField_SDT.getText();
        String diachi = jTextField_DiaChi.getText();
        String loaisanpham = jCheckBox_OPPO.toString();
        
        
        try{
            // Kiểm tra nếu cả hai trường không rỗng
            if (!ten.isEmpty() && !loaisanpham.isEmpty() && !sdt.isEmpty() && !diachi.isEmpty())
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
            else{
                NhaCungCapDTO ncc=new NhaCungCapDTO();
                if(arrNhaCungCap.size()==0){
                    ncc.setMaNCC("NCC001");
                }
                else {
                    NhaCungCapDTO NV = arrNhaCungCap.get(arrNhaCungCap.size()-1);
                    int id = Integer.parseInt(NV.getMaNCC().substring(3));

                    if(id<=9)
                    ncc.setMaNCC("NCC00"+(id+1));
                    else if(id>=10 && id<=99)
                    ncc.setMaNCC("NCC0"+(id+1));
                    else
                    ncc.setMaNCC("NCC"+(id+1));
                }
                ncc.setTenNCC(jTextField_Ten.getText());
                ncc.setDiaChiNCC(jTextField_DiaChi.getText());
                ncc.setSDTNCC(jTextField_SDT.getText());

                nccBLL.addNCC(ncc);
                loadNCClist();
            }

        }
        catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        }
        // Thêm dữ liệu mới vào mô hình

    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        String id = modelNCC.getValueAt(i, 1).toString();
        String name = jTextField_Ten.getText();
        String diachi = jTextField_DiaChi.getText();
        String sdt = jTextField_SDT.getText();
//        String gender = jComboBox_Gender.getSelectedItem().toString();

        nccBLL.UpNCC(id,name,diachi,sdt);

        loadNCClist();

    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        // TODO add your handling code here:
        int i= jTable1.getSelectedRow();
        if(i>=0){
            nccBLL.delNCC(modelNCC.getValueAt(i,1).toString());
            loadNCClist();
        }

    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jComboBox_SearchTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_SearchTypeItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String selectedValue = jComboBox_SearchType.getSelectedItem().toString();

            // Thiết lập giá trị mẫu cho jTextField dựa trên mục đã chọn
            setTextFieldPlaceholder(selectedValue);
        }

    }//GEN-LAST:event_jComboBox_SearchTypeItemStateChanged

    private void jComboBox_SearchTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_SearchTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_SearchTypeActionPerformed

    private void jTextField_SearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SearchFocusGained
        // TODO add your handling code here:
        if(jTextField_Search!=null){
            jTextField_Search.setText("");
            jTextField_Search.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jTextField_SearchFocusGained

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        // TODO add your handling code here:
        String selectedValue = jComboBox_SearchType.getSelectedItem().toString();

        // Lấy giá trị từ jTextField
        String searchText = jTextField_Search.getText().trim();

        if ("Mã Nhà Cung Cấp".equals(selectedValue)) {
            // Tìm kiếm theo ID trong jTable
            searchByID(searchText);
        } else if ("Tên Nhà Cung Cấp".equals(selectedValue)) {
            // Tìm kiếm theo Name trong jTable
            searchByName(searchText);
        } else {
            // Hiển thị thông báo hoặc xử lý lỗi nếu giá trị không hợp lệ
            JOptionPane.showMessageDialog(this, "Giá trị không hợp lệ.");
        }
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jCheckBox_OPPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_OPPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_OPPOActionPerformed

    private void jCheckBox_SAMSUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_SAMSUNGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_SAMSUNGActionPerformed

    private void jCheckBox_APPLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_APPLEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_APPLEActionPerformed

    private void jCheckBox_VIVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_VIVOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_VIVOActionPerformed

    private void jCheckBox_REALMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_REALMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_REALMEActionPerformed
                                                                                               

    private void searchByID(String id) {
    // Thực hiện tìm kiếm theo ID trong jTable và cập nhật kết quả lên jTable
        
        modelNCC.setRowCount(0); // Xóa tất cả dữ liệu hiện có trong jTable
        int stt=1;
        for (int i = 0; i < modelNCC.getRowCount(); i++) {
            String rowData = modelNCC.getValueAt(i, 1).toString(); // Cột ID là cột 0
            if (rowData.equals(id)) {
                // Nếu tìm thấy ID, thêm hàng tương ứng vào jTable
                
                Object[] row = new Object[]{stt,modelNCC.getValueAt(i, 1), modelNCC.getValueAt(i, 2),modelNCC.getValueAt(i, 3),modelNCC.getValueAt(i, 4),modelNCC.getValueAt(i, 5)};
                modelNCC.addRow(row);
                stt++;
                
            }
        }
    }

    private void searchByName(String name) {
        // Thực hiện tìm kiếm theo Name trong jTable và cập nhật kết quả lên jTable
        
        modelNCC.setRowCount(0); // Xóa tất cả dữ liệu hiện có trong jTable
        int stt=1;
        for (int i = 0; i < modelNCC.getRowCount(); i++) {
            String rowData = modelNCC.getValueAt(i, 2).toString(); // Cột Name là cột 1
            if (rowData.equalsIgnoreCase(name)) {
                // Nếu tìm thấy Name, thêm hàng tương ứng vào jTable
                Object[] row = new Object[]{modelNCC.getValueAt(i, 1), modelNCC.getValueAt(i, 2),modelNCC.getValueAt(i, 3),modelNCC.getValueAt(i, 4),modelNCC.getValueAt(i, 5)};
                modelNCC.addRow(row);
                stt++;
            }
        }
    }
    private void setTextFieldPlaceholder(String selectedValue) {
        String placeholderText = ""; // Chuỗi mẫu sẽ được hiển thị trong jTextField

        // Xác định chuỗi mẫu dựa trên mục đã chọn
        if ("Mã Nhà Cung Cấp".equals(selectedValue)) {
            placeholderText = "Ví dụ: NCC001";
        }else if ("Tên Nhà Cung Cấp".equals(selectedValue)) {
            placeholderText = "Ví dụ: CTY Cổ Phần ODS";
        }
        

        // Thiết lập giá trị mẫu cho jTextField
        jTextField_Search.setText(placeholderText);
    }
    public void loadNCClist(){
        arrNhaCungCap = nccBLL.getListNhaCungCap();
//        int a = arrNCC.size();
//        System.out.print(rootPaneCheckingEnabled);
        for(int i = modelNCC.getRowCount()-1;i>=0;i--)
            modelNCC.removeRow(i);
        for(int i = 0; i<arrNhaCungCap.size();i++){
            NhaCungCapDTO em= arrNhaCungCap.get(i);
            int stt= i+1;
            String id= em.getMaNCC();
            String name = em.getTenNCC();
            String address = em.getDiaChiNCC();
            String sdt = em.getSDTNCC();
            
            Object[] row = {stt,id,name,address,sdt};
            modelNCC.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Huy;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JCheckBox jCheckBox_APPLE;
    private javax.swing.JCheckBox jCheckBox_OPPO;
    private javax.swing.JCheckBox jCheckBox_REALME;
    private javax.swing.JCheckBox jCheckBox_SAMSUNG;
    private javax.swing.JCheckBox jCheckBox_VIVO;
    private javax.swing.JComboBox<String> jComboBox_SearchType;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_DiaChi;
    private javax.swing.JTextField jTextField_SDT;
    private javax.swing.JTextField jTextField_Search;
    private javax.swing.JTextField jTextField_Ten;
    // End of variables declaration//GEN-END:variables


}
