/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.SanPhamBLL;
import DAO.SanPhamDAO;
import DTO.SanPhamDTO;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PC
 */
public class SanPhamGUI extends javax.swing.JPanel {
    SanPhamBLL spBLL=new SanPhamBLL();
    
    ArrayList<SanPhamDTO> arrSP=new ArrayList<SanPhamDTO>();
    
    DefaultTableModel modelSP = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // không cho phép chỉnh sửa giá trị các ô trong bảng
        }
    };
    /**
     * Creates new form NhaCungCapGUI
     */
    public SanPhamGUI() {
        
        initComponents();
        //Khởi tạo
        jTable1.setModel(modelSP);
        
        
        modelSP.addColumn("STT");
        modelSP.addColumn("Mã điện thoại");
        modelSP.addColumn("Tên điện thoại");
        modelSP.addColumn("Hãng");
        modelSP.addColumn("Dung lượng");
        modelSP.addColumn("Số lượng");
        modelSP.addColumn("Đơn giá");
        modelSP.addColumn("Hình ảnh");
        
        loadSPlist();
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMaDT = new javax.swing.JLabel();
        jLabelTenDT = new javax.swing.JLabel();
        jLabelHang = new javax.swing.JLabel();
        jLabelDungLuong = new javax.swing.JLabel();
        jLabelGia = new javax.swing.JLabel();
        jTextFieldDungLuong = new javax.swing.JTextField();
        jTextFieldGia = new javax.swing.JTextField();
        jTextFieldMaDT = new javax.swing.JTextField();
        jButtonAnh = new javax.swing.JButton();
        jLabelTimKiem = new javax.swing.JLabel();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jTextFieldTenDT = new javax.swing.JTextField();
        jButtonThem = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonXuatExcel = new javax.swing.JButton();
        jButtonNhapExcel = new javax.swing.JButton();
        jButtonTimKiem = new javax.swing.JButton();
        jTextFieldHinhAnh = new javax.swing.JTextField();
        jLabelHinhAnh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxHang = new javax.swing.JComboBox<>();
        jLabelAnh = new javax.swing.JLabel();
        jButtonLamMoi = new javax.swing.JButton();

        jLabelMaDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMaDT.setText("Mã điện thoại");

        jLabelTenDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTenDT.setText("Tên điện thoại");

        jLabelHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelHang.setText("Hãng");

        jLabelDungLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDungLuong.setText("Dung lượng");

        jLabelGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelGia.setText("Giá");

        jTextFieldDungLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldDungLuong.setPreferredSize(new java.awt.Dimension(60, 30));

        jTextFieldGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldGia.setPreferredSize(new java.awt.Dimension(60, 30));

        jTextFieldMaDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldMaDT.setEnabled(false);
        jTextFieldMaDT.setPreferredSize(new java.awt.Dimension(60, 30));

        jButtonAnh.setText("Chọn ảnh");
        jButtonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnhActionPerformed(evt);
            }
        });

        jLabelTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTimKiem.setText("Tìm kiếm");

        jTextFieldTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTimKiemActionPerformed(evt);
            }
        });

        jTextFieldTenDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTenDT.setPreferredSize(new java.awt.Dimension(60, 30));

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonXuatExcel.setText("Xuất Excel");

        jButtonNhapExcel.setText("Nhập Excel");

        jButtonTimKiem.setText("Tìm kiếm");

        jTextFieldHinhAnh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldHinhAnh.setPreferredSize(new java.awt.Dimension(60, 30));
        jTextFieldHinhAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHinhAnhActionPerformed(evt);
            }
        });

        jLabelHinhAnh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelHinhAnh.setText("Hình ảnh");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBoxHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IPhone", "Samsung", " " }));
        jComboBoxHang.setPreferredSize(new java.awt.Dimension(60, 30));

        jLabelAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelAnh.setPreferredSize(new java.awt.Dimension(100, 100));

        jButtonLamMoi.setText("Làm mới");
        jButtonLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelHang)
                                    .addComponent(jLabelDungLuong))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelMaDT)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMaDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDungLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelHinhAnh)
                                .addGap(57, 57, 57)
                                .addComponent(jTextFieldHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelGia)
                                .addGap(93, 93, 93)
                                .addComponent(jTextFieldGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTenDT)
                                .addGap(26, 26, 26)
                                .addComponent(jTextFieldTenDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLamMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonXuatExcel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNhapExcel)
                        .addGap(50, 50, 50)
                        .addComponent(jLabelAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addGap(18, 18, 18)
                .addComponent(jButtonAnh)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabelTimKiem)
                .addGap(28, 28, 28)
                .addComponent(jTextFieldTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonTimKiem)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaDT)
                    .addComponent(jTextFieldMaDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTenDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTenDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHang)
                    .addComponent(jLabelGia)
                    .addComponent(jTextFieldGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDungLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnh)
                    .addComponent(jTextFieldHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHinhAnh)
                    .addComponent(jLabelDungLuong))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonThem)
                            .addComponent(jButton2)
                            .addComponent(jButtonXoa)
                            .addComponent(jButtonXuatExcel)
                            .addComponent(jButtonNhapExcel)
                            .addComponent(jButtonLamMoi)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTimKiem)
                    .addComponent(jButtonTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimKiemActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        String masp = generateMaDT();
        jTextFieldMaDT.setText(masp);
        String tensp= jTextFieldTenDT.getText();
        String hang = jComboBoxHang.getSelectedItem().toString();
        String dungluong = jTextFieldDungLuong.getText();
        String gia= jTextFieldGia.getText();
        String hinhanh= jTextFieldHinhAnh.getText();
        
        try{
            // Kiểm tra nếu cả hai trường không rỗng
            if (masp.isEmpty() || tensp.isEmpty() || hang.isEmpty() || dungluong.isEmpty() || gia.isEmpty() || hinhanh.isEmpty())
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
            else{
                SanPhamDTO sp=new SanPhamDTO();
//                if(arrSP.size()==0){
//                    sp.setMaSP("SP001");
//                }
//                else {
//                    SanPhamDTO SP = arrSP.get(arrSP.size()-1);
//                    int id = Integer.parseInt(SP.getMaSP().substring(3));
//
//                    if(id<=9)
//                    sp.setMaSP("SP00"+(id+1));
//                    else if(id>=10 && id<=99)
//                    sp.setMaSP("SP0"+(id+1));
//                    else
//                    sp.setMaSP("SP"+(id+1));
//                }
                sp.setMaSP(masp);
                sp.setTenSP(jTextFieldTenDT.getText());
                sp.setHang(jComboBoxHang.getSelectedItem().toString());
                sp.setDungLuong(jTextFieldDungLuong.getText());
                sp.setDonGia(Integer.parseInt(jTextFieldGia.getText()));
                sp.setHinhAnh(jTextFieldHinhAnh.getText());

                spBLL.addSP(sp);
                loadSPlist();
            }
    }//GEN-LAST:event_jButtonThemActionPerformed
    catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        }
    }

    private void jTextFieldHinhAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHinhAnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHinhAnhActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
        // Lấy thông tin của dòng được chọn
        String masp = jTable1.getValueAt(selectedRow, 1).toString();
        String tensp = jTable1.getValueAt(selectedRow, 2).toString();
        String hang = jTable1.getValueAt(selectedRow, 3).toString();
        String dungluong = jTable1.getValueAt(selectedRow, 4).toString();
        String gia = jTable1.getValueAt(selectedRow, 6).toString();
        String hinhanh = jTable1.getValueAt(selectedRow, 7).toString();

        // Cập nhật các trường văn bản và trường khác với thông tin của dòng được chọn
        jTextFieldMaDT.setText(masp);
        jTextFieldTenDT.setText(tensp);
        jComboBoxHang.setSelectedItem(hang);
        jTextFieldDungLuong.setText(dungluong);
        jTextFieldGia.setText(gia);
        jTextFieldHinhAnh.setText(hinhanh);
        
        File file = new File(hinhanh);
        ImageIcon imageIcon = new ImageIcon(file.getAbsolutePath());
        Image image = imageIcon.getImage();
        Image scaledImage = image.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
        jLabelAnh.setIcon(scaledImageIcon);
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnhActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Chọn file ảnh");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG, PNG, GIF Images", "jpg", "png", "gif");
        chooser.setFileFilter(filter);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String imagePath = chooser.getSelectedFile().getPath();
            jTextFieldHinhAnh.setText(imagePath);
    }//GEN-LAST:event_jButtonAnhActionPerformed
    }
    private void jButtonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLamMoiActionPerformed
        jTextFieldMaDT.setText("");
        jTextFieldTenDT.setText("");
        jComboBoxHang.setSelectedIndex(0);
        jTextFieldDungLuong.setText("");
        jTextFieldGia.setText("");
        jTextFieldHinhAnh.setText("");
        jLabelAnh.setIcon(null); // Clear the displayed image
    }//GEN-LAST:event_jButtonLamMoiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = jTable1.getSelectedRow();
        String id = modelSP.getValueAt(i, 1).toString();
        String name = jTextFieldTenDT.getText();
        String dungluong = jTextFieldDungLuong.getText();
        int soluong = 0;
        int dongia= Integer.parseInt(jTextFieldGia.getText());
        String hinhanh= jTextFieldHinhAnh.getText();
        String hang = jComboBoxHang.getSelectedItem().toString();
        
        
        spBLL.UpSP(id,name,hang,dungluong,soluong,dongia,hinhanh);
        	
        
        loadSPlist();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        int i= jTable1.getSelectedRow();
        if(i>=0){
            spBLL.delSP(modelSP.getValueAt(i,1).toString());
            loadSPlist();
        }
    }//GEN-LAST:event_jButtonXoaActionPerformed

    public void loadSPlist(){
        arrSP = spBLL.getListSanPham();
//        int a = arrSP.size();
//        System.out.print(rootPaneCheckingEnabled);
        for(int i = modelSP.getRowCount()-1;i>=0;i--)
            modelSP.removeRow(i);
        for(int i = 0; i<arrSP.size();i++){
            SanPhamDTO em= arrSP.get(i);
            int stt= i+1;
            String masp= em.getMaSP();
            String tensp = em.getTenSP();
            String hang = em.getHang();
            String dungluong = em.getDungLuong();
            int soluong=em.getSoLuong();
            int dongia=em.getDonGia();
            String hinhanh = em.getHinhAnh();
            Object[] row = {stt,masp,tensp,hang,dungluong,soluong,dongia,hinhanh};
            modelSP.addRow(row);
        }
    }
    

// Tạo hàm để tạo mã tự động
    private String generateMaDT() {
        if (arrSP.size() == 0) {
            return "SP001";
        } else {
            SanPhamDTO lastSP = arrSP.get(arrSP.size() - 1);
            String lastMaSP = lastSP.getMaSP();
            int lastID = Integer.parseInt(lastMaSP.substring(2)); // Lấy phần số từ mã hiện tại
            int newID = lastID + 1;
            String newMaSP = "SP" + String.format("%03d", newID); // Format mã mới với đủ 3 chữ số
            return newMaSP;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAnh;
    private javax.swing.JButton jButtonLamMoi;
    private javax.swing.JButton jButtonNhapExcel;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JButton jButtonXuatExcel;
    private javax.swing.JComboBox<String> jComboBoxHang;
    private javax.swing.JLabel jLabelAnh;
    private javax.swing.JLabel jLabelDungLuong;
    private javax.swing.JLabel jLabelGia;
    private javax.swing.JLabel jLabelHang;
    private javax.swing.JLabel jLabelHinhAnh;
    private javax.swing.JLabel jLabelMaDT;
    private javax.swing.JLabel jLabelTenDT;
    private javax.swing.JLabel jLabelTimKiem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDungLuong;
    private javax.swing.JTextField jTextFieldGia;
    private javax.swing.JTextField jTextFieldHinhAnh;
    private javax.swing.JTextField jTextFieldMaDT;
    private javax.swing.JTextField jTextFieldTenDT;
    private javax.swing.JTextField jTextFieldTimKiem;
    // End of variables declaration//GEN-END:variables
}
