/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author PC
 */
public class SanPhamGUI extends javax.swing.JPanel {

    /**
     * Creates new form SanPhamGUI
     */
    public SanPhamGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMaDT = new javax.swing.JLabel();
        jLabelTenDT = new javax.swing.JLabel();
        jLabelHang = new javax.swing.JLabel();
        jLabelMau = new javax.swing.JLabel();
        jLabelDungLuong = new javax.swing.JLabel();
        jLabelSoLuong = new javax.swing.JLabel();
        jLabelGia = new javax.swing.JLabel();
        jTextFieldDungLuong = new javax.swing.JTextField();
        jTextFieldMau = new javax.swing.JTextField();
        jTextFieldGia = new javax.swing.JTextField();
        jComboBoxHang = new javax.swing.JComboBox<>();
        jTextFieldMaDT = new javax.swing.JTextField();
        jButtonAnh = new javax.swing.JButton();
        jLabelTimKiem = new javax.swing.JLabel();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jTextFieldTenDT = new javax.swing.JTextField();
        jTextFieldSoLuong = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabelMaDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMaDT.setText("Mã điện thoại");

        jLabelTenDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTenDT.setText("Tên điện thoại");

        jLabelHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelHang.setText("Hãng");

        jLabelMau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMau.setText("Màu");

        jLabelDungLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDungLuong.setText("Dung lượng");

        jLabelSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSoLuong.setText("Số lượng");

        jLabelGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelGia.setText("Giá");

        jTextFieldDungLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextFieldMau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextFieldGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jComboBoxHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHangActionPerformed(evt);
            }
        });

        jTextFieldMaDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButtonAnh.setText("Chọn ảnh");

        jLabelTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTimKiem.setText("Tìm kiếm");

        jTextFieldTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTimKiemActionPerformed(evt);
            }
        });

        jTextFieldTenDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextFieldSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHang)
                            .addComponent(jLabelDungLuong)
                            .addComponent(jLabelMaDT)
                            .addComponent(jLabelMau))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldMaDT)
                            .addComponent(jTextFieldDungLuong)
                            .addComponent(jTextFieldMau))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTenDT)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTenDT, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelGia)
                                    .addComponent(jLabelSoLuong))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                    .addComponent(jTextFieldGia)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabelTimKiem)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addComponent(jButtonAnh)))
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaDT)
                    .addComponent(jTextFieldMaDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTenDT)
                    .addComponent(jTextFieldTenDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHang)
                    .addComponent(jComboBoxHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSoLuong))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDungLuong)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDungLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelGia)
                        .addComponent(jTextFieldGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMau))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnh)
                    .addComponent(jLabelTimKiem)
                    .addComponent(jTextFieldTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxHangActionPerformed

    private void jTextFieldTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnh;
    private javax.swing.JComboBox<String> jComboBoxHang;
    private javax.swing.JLabel jLabelDungLuong;
    private javax.swing.JLabel jLabelGia;
    private javax.swing.JLabel jLabelHang;
    private javax.swing.JLabel jLabelMaDT;
    private javax.swing.JLabel jLabelMau;
    private javax.swing.JLabel jLabelSoLuong;
    private javax.swing.JLabel jLabelTenDT;
    private javax.swing.JLabel jLabelTimKiem;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDungLuong;
    private javax.swing.JTextField jTextFieldGia;
    private javax.swing.JTextField jTextFieldMaDT;
    private javax.swing.JTextField jTextFieldMau;
    private javax.swing.JTextField jTextFieldSoLuong;
    private javax.swing.JTextField jTextFieldTenDT;
    private javax.swing.JTextField jTextFieldTimKiem;
    // End of variables declaration//GEN-END:variables
}
