/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.TaiKhoanBLL;
import DTO.TaiKhoanDTO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Trung Hiếu
 */
public class TaiKhoanGUI extends javax.swing.JPanel {
    TaiKhoanBLL tkBLL = new TaiKhoanBLL();
    ArrayList<TaiKhoanDTO> arrTaiKhoan = new ArrayList<TaiKhoanDTO>();
    DefaultTableModel modelTK = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // không cho phép chỉnh sửa giá trị các ô trong bảng
    }
    };
    /**
     * Creates new form TaiKhoanGUI
     */
    
    public TaiKhoanGUI() {
        initComponents();
        jTableTaiKhoan.setModel(modelTK);
        modelTK.addColumn("Mã Tài Khoản");
        modelTK.addColumn("Tên đăng nhập");
        modelTK.addColumn("Mật khẩu");       
        modelTK.addColumn("Trạng thái");
        loadTKList();
    }
    public void loadTKList(){        
        DefaultTableModel model = (DefaultTableModel) jTableTaiKhoan.getModel();
        model.setRowCount(0); // Xóa hết dữ liệu trong jTable1
        arrTaiKhoan = tkBLL.getListTaiKhoan();

        for(int i = 0; i<arrTaiKhoan.size();i++){
            TaiKhoanDTO tk = arrTaiKhoan.get(i);
            String id= tk.getMaTK();
            String username = tk.getTenDangNhap();
            String password = tk.getMatKhau();            
            int trangthai = tk.getTrangThai();
            
            Object[] row = {id,username,password,trangthai};
            modelTK.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_tendangnhap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField_matkhau = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_quyen = new javax.swing.JComboBox<>();
        jComboBox_trangthai = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        addTkBtn = new javax.swing.JButton();
        editTkBtn = new javax.swing.JButton();
        delTkBtn = new javax.swing.JButton();
        searchTkBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTaiKhoan = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        jLabel2.setText("Tên đăng nhập:");

        jLabel3.setText("Mật khẩu:");

        jPasswordField_matkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_matkhauActionPerformed(evt);
            }
        });

        jLabel4.setText("Quyền:");

        jComboBox_quyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        jComboBox_quyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_quyenActionPerformed(evt);
            }
        });

        jComboBox_trangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Offline", "Online" }));
        jComboBox_trangthai.setToolTipText("");
        jComboBox_trangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_trangthaiActionPerformed(evt);
            }
        });

        jLabel5.setText("Trạng thái:");

        addTkBtn.setText("Thêm");
        addTkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTkBtnActionPerformed(evt);
            }
        });

        editTkBtn.setText("Sửa");

        delTkBtn.setText("Xóa");
        delTkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delTkBtnActionPerformed(evt);
            }
        });

        searchTkBtn.setText("Tìm kiếm");

        jTableTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTaiKhoan);

        jTextField3.setText("jTextField3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(addTkBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPasswordField_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_tendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(editTkBtn)
                                .addGap(144, 144, 144)
                                .addComponent(delTkBtn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(63, 63, 63)
                                        .addComponent(jComboBox_trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox_quyen, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(searchTkBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_tendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_quyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox_trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTkBtn)
                    .addComponent(editTkBtn)
                    .addComponent(delTkBtn))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý tài khoản", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Mã tài khoản:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Phân quyền:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý phân quyền", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(431, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_quyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_quyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_quyenActionPerformed

    private void addTkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTkBtnActionPerformed
        // TODO add your handling code here:
        String tendangnhap = jTextField_tendangnhap.getText();
        String matkhau = String.valueOf(jPasswordField_matkhau.getPassword());
        String quyenTemp = jComboBox_quyen.getSelectedItem().toString();
        int quyen;
        if (quyenTemp == "Admin") quyen = 1;
            else quyen = 2;
        String trangthaiTemp = jComboBox_trangthai.getSelectedItem().toString();
        int trangthai;
        if (trangthaiTemp == "Offline") trangthai = 0;
            else trangthai = 1;
        try{
            // Kiểm tra nếu cả hai trường không rỗng
            if (tendangnhap.isEmpty() || matkhau.isEmpty() || trangthaiTemp.isEmpty()) 
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
            else{
                TaiKhoanDTO tk = new TaiKhoanDTO();
                if(arrTaiKhoan.size()==0 && quyen == 2){
                    tk.setMaTK("ST001");
                } else if(arrTaiKhoan.size()==0 && quyen == 1){
                    tk.setMaTK("AD001");
                }
                else {
	                int id = arrTaiKhoan.size();
	                if(quyen == 2){
                            if(id<=9 && id>0)
                                tk.setMaTK("ST00"+(id+1));
                            else if(id>=10 && id<=99)
                                tk.setMaTK("ST0"+(id+1));
                                else
                                    tk.setMaTK("ST"+(id+1));
                        }
                            else if(quyen == 1){
                                if(quyen == 1){
                                    if(id<=9)
                                        tk.setMaTK("AD00"+(id+1));
                                    else if(id>=10 && id<=99)
                                        tk.setMaTK("AD0"+(id+1));
                                        else
                                            tk.setMaTK("AD"+(id+1));
                        }
                        }
	                
                }                
                tk.setTenDangNhap(jTextField_tendangnhap.getText());
                tk.setMatKhau(String.valueOf(tk));
                String state = jComboBox_quyen.getSelectedItem().toString();
                if(state.equals("Admin")) tk.setTrangThai(1);
                    else tk.setTrangThai(2);
                
                
                tkBLL.AddTK(tk);
                loadTKList();
            }
            
        }catch(Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        }
          
    }//GEN-LAST:event_addTkBtnActionPerformed

        
    private void jComboBox_trangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_trangthaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_trangthaiActionPerformed

    private void jPasswordField_matkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_matkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_matkhauActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void delTkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delTkBtnActionPerformed
        // TODO add your handling code here:
        int i= jTableTaiKhoan.getSelectedRow();
        if(i>=0){
            tkBLL.delTK(modelTK.getValueAt(i,1).toString());
            loadTKList();
        }
    }//GEN-LAST:event_delTkBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTkBtn;
    private javax.swing.JButton delTkBtn;
    private javax.swing.JButton editTkBtn;
    private javax.swing.JComboBox<String> jComboBox_quyen;
    private javax.swing.JComboBox<String> jComboBox_trangthai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_matkhau;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableTaiKhoan;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField_tendangnhap;
    private javax.swing.JButton searchTkBtn;
    // End of variables declaration//GEN-END:variables
}
